discord/bot.go, main.go, sample.env
Removes the need to always type ```.au t ...``` when starting => most servers have dedicated channels per game anyway
=> Added default voice channel to track

.gitignore, TODO.org, autoupdate.go, capture.go, capture/capture.go, capture/colors.go, capture/keyWords.go, capture/socketClient.go, discord.go, discord/bot.go, discord/guild.go, sample.env
Draft PR to enable support for moving players who are dead into a separate voice channel.
I opened this as a draft because I still need to get a solid testing environment setup before battle testing this.
There are a decent amount of linting and warning fixes in here as well, happy to put them into a separate PR. I figured it would just be easier to do it all at once :)
Some of the linting rules are sorta dumb IMO, but it is what ships stock with the vs-code extension so I said f'it hah.
Feel free to leave any feedback, ask any questions, etc!
=> Dead player voice channel [DRAFT]

TODO.org, discord/bot.go, discord/colors.go, discord/emoji.go, discord/guild.go, discord/message_handlers.go
=> Game end message

TODO.org, discord/guild.go, discord/helpers.go, discord/message_handlers.go, discord/user.go
this allows support for deafen+mute for players who are dead.
this is much cleaner than moving between channels since we don't need to muck with the track command at all
=> Add support for deafening and muting

discord/bot.go, discord/guild.go, discord/message_handlers.go, discord/responses.go, main.go
=> Connect codes, misc fixes, help text

discord/bot.go, discord/responses.go, discord/userDataSet.go, game/amongusdata.go, logs.txt
This addresses the 2 issues I filed earlier today.
- Fixed inconsistent capitalization of embed message fields
- Adding linked player counter on the embedded field LinkedPlayers/LobbyPlayers
=> Linked Player Counter

discord/bot.go, discord/guild.go, discord/message_handlers.go, game/state.go, main.go
Perms functioning as described in 2.2.1 -_-
=> Permissions fixes

Dockerfile
Made a new Dockerfile with a staged build process
=> make a staged Dockerfile to reduce imagesize to around 7mb 

discord/bot.go, game/state.go
This adds a SocketIO event, that allows the capture program to set the room code that is displayed in the status message in Discord.
See https://github.com/denverquane/amonguscapture/pull/34
=> Automatically set room code

.gitignore, README.md, discord/bot.go, discord/message_handlers.go, main.go
This will allow for a different port if behind a load balancer (or use on heroku)
=> Add ext port

README.md
Makes formatting consistent and adds "Silence Among Us".
=> Docs: Update similar projects

discord/guild.go
Reverts denverquane/amongusdiscord#132
@auyer My mistake, totally forgot an important part of the functionality that's going to necessitate a revert.
The priority queue is removed as part of your PR, but this is important functionality that needs to be preserved. Reason being is that if we mute/unmute, say, only 5 of the 10 total users (in one fell swoop, as part of the Discord API rate limits), *we need to ensure those 5 are users that can't leak information to other users*. This is really important, and your new approach -while faster, albeit not solving the *true* dominant bottleneck- removes this important functionality. 
The approach doesn't guarantee that the users who need to be muted/unmuted first are actually done so before any other users, and so I need to revert it.
=> Revert "Update voice status using "Channel Workers""

.github/workflows/docker-build.yml
Add `DOCKER_TOKEN` with value  from https://hub.docker.com/settings/security to https://github.com/denverquane/amongusdiscord/settings/secrets
=> Add .github/workflows/docker-build.yml

README.md
In the ## Easiest sections I have changed steps 5-7 to reflect some of the new functionality in recent updates. The steps now recommend the easier automatic launch of the capture executable while still explaining manually launching the capture executable.
=> Updated README.md for clarity of automatic launch

.github/workflows/goreleaser.yml, .goreleaser.yaml, main.go
See https://github.com/chauffer/amongusdiscord/releases/tag/v2.3.4 for an example
=> Add goreleaser

README.md
I'm adding the information on how to install on unRAID.
=> Adding unRAID install information

discord/message_handlers.go
amonguscapture has changed to only having one download file now
=> Fix capture download URL

README.md
Cleaned up the basic requirements and added remote hosted bot requirements above the docker instructions
=> updated requirements list in readme

.goreleaser.yaml
People are downloading it thinking it's the config file.
=> goreleaser: Disable checksum

discord/commands.go
Fixed a crash when an application error
=> fix(commands): fixed runtime error: index out of range

app.json
These changes are to update the Heroku deployment JSON with the new environment variables from the recent branch. Feel free to add any new variables I may have missed.
=> Update app.json with changed environment variables for Heroku deployment

locales/active.de.toml
Some translations seemed to be from google translate, so I improved these. **Also used the typo-fixes from @bin101 provided in #218 (pull request).**
=> German translation fix: typos, grammatical errors

locales/active.nl.toml
I translated all the text to Dutch
=> Create active.nl.toml (Dutch translation)

locales/active.ru.toml
Hey @denverquane,
As I promised - Russian localization was reworked.
Now it looks better UwU (dat zu locale is awesome).
Special thanks to @xTCry  for his work! Without his help, it would have been harder.
=> Russian language reworked: typos and gramm errors fix

discord/ascii.go
This should now be right. If it’s not correct me please ^^
=> Typo-fix: ascii command

locales/active.de.toml, locales/active.fr.toml, locales/active.nl.toml, locales/active.ru.toml, locales/active.zu.toml
Hi,
my first small contribution. Added Icons for Room Code and Region in all languages.
=> Localization: Added Icons to Roomcode/Region String

docker-compose.yml
=> docker-compose: add WORKER_BOT_TOKENS var

locales/active.it.toml
I noticed that I translated some sentences in a bad way and i fixed them.
=> Fixed some incorrect translations

README.md
Added 2.4.3 self hosting and galactus thingys to the readme, and made the file links relative and added a few more
=> Added... stuff... to the readme

locales/active.fr.toml
Added all the new variables for french translations
Mainly about Stats and Premium stuff
=> Fr lang Update 6.3.2

locales/active.fr.toml
Reverts denverquane/automuteus#306
Whoops, merged before looking at this closely.
Needs the correct formatting for merge; this is not generated with the goi18n tool
=> Revert "Fr lang Update 6.3.2"

README.md, discord/bot.go, discord/message_handlers.go, storage/guildSettings.go, storage/redis.go
Adds self-hosting environment variable for "Global Prefix"
=> Global prefix

amongus/playerData.go, discord/eventHandler.go, discord/gameStateMessage.go, discord/message_handlers.go, discord/setting/settings.go, discord/setting_handlers.go, discord/voice.go, go.mod, go.sum, storage/guildSettings.go
Adds spectator setting to treat spectators like dead players according to voicerules (defaults to off)
=> Spectator Setting

discord/stats.go, storage/postgresTypes.go, storage/statsQueries.go
When a user ask to show his stats.
It will display his best and worst mate in Impostor and Crewmate
=> Add Best/Worst Stats for Impostor and Crewmate mate

discord/stats.go, storage/statsQueries.go
Add worst/best impostor/Crewmate stats for the guild
=> Add worst/best Impostor/Crewmate stats for the guild

discord/stats.go, storage/statsQueries.go
Fix stats weren't getting your real teammate.
Reduce Impostor stats to 2+ games
=> Fix stats weren't getting your real teammate.

discord/stats.go, storage/postgresTypes.go, storage/statsQueries.go
Showing new stats for Impostor and Crewmate
=> New data to show the exiled / killed impostor/crewmate

discord/responses.go
=> fix: #403 Fix invalid permission for priority mute bot

README.md
Thank you for using this bot everyday.
This commit is updating README.md for using map command.
If it is ok, I want to update all commands readme.
Please check my English.
=> Update README.md for bot command map

storage/statsQueries.go
=> fix(stats): #408 Add guild id filter for FirstTarget stats

discord/command/commands.go
=> Fix typo in command aliases

discord/command/commands.go, locales/active.en.toml, locales/active.it.toml, locales/active.ja.toml, locales/active.pl.toml, locales/active.zu.toml
A trivial PR, just add ", airship" to the help message 🚀
=> Update help message for the new airship map

TODO.txt, discord/responses.go, discord/setting_handlers.go, go.mod, go.sum
Required for v7 version of denverquane/automuteus#418
We will need to modify go.mod additionally, so once automuteus/utils#2 is merged and tagged, will modify this PR as well.
=> Add new option: DisplayRoomCode (v7)

README.md
=> feat: add pointers for someone who want to develop

main.go
This is for **slash-commands** branch.
Add support to use Guild Commands on multiple guilds for self-hosted instance.
I think the Global Commands is proper way to use commands in multiple guilds, but it is a bit frustrating since the command will only be available after a maximum of one hour.
=> feat: add multiple guilds support for guild commands

storage/postgres.sql
=> fix: add vote_time_unix column if not exists (#485)

Dockerfile, bot/api.go, bot/command/new.go, bot/helpers.go, bot/slash_commands.go, locales/active.en.toml, locales/active.fr.toml, templates/link.tmpl
Feat: Add link to open directly AmongUsCapture instead of copying and pasting in your browser
=> Feat: Add link to open directly AmongUsCapture
