- discord/bot.go
- discord/guild.go
- discord/helpers.go
- discord/message_handlers.go
- discord/voiceBehavior.go
- game/state.go
- main.go
Prioritize applying changes to users who need to be muted/unmuted first to prevent overlap between users who shouldn't be able to hear eachother. Synchronously wait for ALL users to have voice changes applied BEFORE updating the status message (Rate-limiting considerations)
> Api ordering

- README.md
- app.json
- main.go
Added the ability for users to be able to easily deploy the Among Us discord bot to Heroku.
Not sure why the env var "SERVER_PORT" was picked but changing it to "PORT" allows the app to easily work with Heroku.
> Added "Deploy to Heroku" Functionality

- .gitignore
- discord/message_handlers.go
This allows setting
`SERVER_URL=https://api.example.com:8443`
instead of
`SERVER_URL=https://api.example.com` and
`EXT_PORT=8443`
> Allow overriding external port in SERVER_URL

- discord/message_handlers.go
This adds information for manually linking the capture to the embed sent to the user that started the game
> Manual linking info

- discord/guild.go
This PR changes the way the Voice States are updated.
The current procedure is slow, and unnecessarily complicated.
I've tested a few different ways to do this, and came to the conclusion that the priority queue slows down this process, and although it is possible to have both the priority queue and the "worker", it only makes the process slower.
I invite you to test this for yourself, but I understand this is hard to measure. I've spent a few hours testing with a 10 players party (they were very patient).
Users were given a priority ranking, inserted in a heap, and later poped from it, and a sync group was used to ensure the higher priority users were updated first.
A number of "workers" are started, each one in a different go routine. Each one is capable of updating every user, but …
> Update voice status using "Channel Workers"

- go.mod
Current go.mod's method of requiring go 1.15 doesn't seem to work with Heroku; it still deploys 1.12 which causes the build to fail:
```
-----> Go app detected
-----> Fetching jq... done
-----> Fetching stdlib.sh.v8... done
-----> 
Detected go modules via go.mod
-----> 
Detected Module Name: github.com/denverquane/amongusdiscord
-----> 
!!    The go.mod file for this project does not specify a Go version
!!    
!!    Defaulting to go1.12.17
!!    
!!    For more details see: https://devcenter.heroku.com/articles/go-apps-with-modules#build-configuration
!!    
-----> New Go Version, clearing old cache
-----> Installing go1.12.17
-----> Fetching go1.12.17.linux-amd64.tar.gz... done
...
discord/message_handlers.go:55:27: urlregex.SubexpIndex undefined (type *regexp.Regexp has no field or …
```
> Fix go version requirement for Heroku

- app.json
This modified app.json fixes the need to restart the app immediately after deployment by specifying the necessary environment variables before deployment. 
It also fixes the build issue where Heroku defaults to an older version of Go by automatically selecting Go 1.15 using the GOVERSION env var. This way, instead of modifying go.mod, all Heroku deployment information can stay within app.json.
The deployment also requires that you have at least one Discord bot token before building the app. 
I was able to successfully deploy this app on Heroku using this app.json and communicate with the capture using the DM link sent. 
Current Heroku deployment page:
Proposed Heroku deployment page:
> Modify app.json to include GOVERSION and all environment variables

- storage/guildSettings.go
So this is part of a larger issue, and fixes it partially:
The `HasAdminPerms` and `HasRolePerms` functions take a guild Member from bot.py's message handler:
https://github.com/denverquane/amongusdiscord/blob/137dc9ac234ccc3a6a54342510e9d515d1c0d1a5/discord/bot.go#L964
While the `Member` property does come from the MessageCreate event and is available, the `User` property on it is missing. This is documented in the [Discord GuildMember docs](https://discord.com/developers/docs/resources/guild#guild-member-object):
> The field user `user` won't be included in the member object attached to `MESSAGE_CREATE` and `MESSAGE_UPDATE` gateway events.
So what that means is right now, all calls to `HasAdminPerms` and `HasRolePerms` are failing, as `mem.User` is nil. To fix this we would probably …
> Fix HasRolePerms

- .github/workflows/docker-build.yml
All Pull Requests currently run the `docker-build.yml` task, which always fails due to the `DOCKER_TOKEN` not being available, making PRs fail one of the checks and being marked with a cross. This should probably not even be attempted in PRs (or alternatively just the docker build should be attempted, not the push to Docker Hub).
> Disable docker-build.yml in PRs

- discord/bot.go
This PR just adds a simple response to the root url on the internal server.
I'm trying to find a way to keep my heroku instance alive and the best way I found was through https://cron-job.org/. Unfortunately cron-job.org will disable jobs with failing requests and it understandably interprets the 404 response from AutoMuteUs as a failed rejest. This PR creates an endpoint to get non error responses from the server allowing us to hook it to cron-job.org for keeping heroku instances alive.
> Avoiding 404 error on root requests

- .dockerignore
- Dockerfile
As it is now, it's a bit messy to deploy this with docker. I've set it up so, by default, you can cleanly set up volumes to allow taking the container down without losing data, etc.
Plus, I've ran amended the Dockerfile as suggested by hadolint and implemented a non-root user in line with the principle of least privilege.
Is the commit and version information really needed in the binary shipped with docker? As the container itself should already be tagged with this info. If this is not the case a further optimisation can be made by ignoring `.git`.
Problems fixed:
```
4 DL3019 Use the `--no-cache` switch to avoid the need to use `--update` and remove `/var/cache/apk/*` when done installing packages
17 SC2046 Quote this to prevent word splitting.
24 DL3006 Always tag the version of an …
```
> Docker updating

- discord/message_handlers.go
If AdminUserIDs contains a user id and PermissionRoleIDs is still empty, only the guild owner had admin rights and the user id in AdminUserIDs has no effect.
Fixes #211
> fix(permissions):

- discord/ascii.go
So if more than 1 impostor remains, it put's out "Impostors remain" instead of "Impostor remains"
> Ascii-Easteregg: "singular/plural" output matching to count 

- locales/active.de.toml
- locales/active.en.toml
- locales/active.fr.toml
- locales/active.nl.toml
- locales/active.zu.toml
one typo is all over the place
> typo-fix in de/en/fr/nl/zu language (sing./pl. mistake)

- discord/message_handlers.go
Since the executable is now in a ZIP folder, the download link is changed to https://github.com/denverquane/amonguscapture/releases/latest/download/amonguscapture.zip
> Rectify amonguscapture download link

- sample.env
6.0.0 provided as workaround, goreleaser need to be reconfigured
> sample.env: AUTOMUTEUS_TAG hotfix

- locales/active.fr.toml
Fix wrong French translation for the stats of the server.
The command “serveur" doesn't exist, instead it’s “server"
> Fix wrong French translation for the stats of the server.

- README.md
I maintain a package/"Port" of AutoMuteUs in the FreeBSD Ports tree as [`games/automuteus`](https://www.freshports.org/games/automuteus/). We should mention this in the README.md.
> AutoMuteUs exists in the FreeBSD Ports Tree: Add to README.md

- storage/statsQueries.go
The query only check the best win rate which is wrong to get the best accurate result.
The query didn't take in account the most game win/lost and total game
> Fix stats worst/best.

- discord/command_handlers.go
- discord/message_handlers.go
- discord/responses.go
- discord/stats.go
- discord/voice.go
- storage/postgres.go
**This PR is required for v6 only.**
Since the check was [already implemented in v7](https://github.com/denverquane/automuteus/commit/80ef2096bbd5a7ec541445383e222a3af29fd06b), this PR implement it the similar way as in v7.
Tested in my testbed using faked DB and `AUTOMUTEUS_OFFICIAL`, `MAX_ACTIVE_GAMES` in following situations;
- Free Tier, Premium Tier (Expired), Premium Tier (Active)
- Self-Hosted
> fix: improve expiration check for the premium status (v6)

- discord/command_handlers.go
**This PR is required for v7 only.**
Fixes the issue that the `premium invite` command shows the invitation link even if the premium tier has expired.
> fix: add expiration check for the invite command (v7)

- README.md
The current readme said that it only supports the steam version of the game, but the capture repository says that it supports all the releases.
> clarify support for releases

- discord/command/dm.go
- discord/slash_commands.go
This is a PR for **slash-command** branch.
The Global Commands are available in DMs, so it should be blocked to avoid unintended issue when the `i.GuildID` is empty.
> An individual app's global commands are also available in DMs if that app has a bot that shares a mutual guild with the user.
> <https://discord.com/developers/docs/interactions/application-commands#registering-a-command>
If you have the plan to handle this or your code is under developing about this, feel free to reject this PR 🚀
> fix: block global commands from dm

- discord/setting/settings.go
**This PR is for `slash-commands` branch**.
Add `ApplicationCommandOptionRole` type to be able to handle Role IDs as argments for slash commands, since the command `/settings operator-roles role:@hoge` makes the `Option` with this type.
Currently the command doesn't works well since any roles always determined as `""`.
> fix: add role type which can be handled as args for slash-command

- discord/slash_commands.go
In the current implementation, the big hourglass ⌛ remains forever if;
- the command takes over 2 seconds,
- and the updated followup message is `embed` type instead of `content` type
since the empty content `""` doesn't replace existing message content. This is a bit annoying.
This PR replace this hourglass with `\u200b` if the updated followup message contains empty content `""`.
> fix: remove hourglass from followup message

- README.md
- locales/active.en.toml
Closes automuteus/utils#5
Thanks for adding locales on utils repository.
If this make some conflicts with your working tree or if you know more appropriate way, it's ok to revoke this.
> fix: add strings for translation from utils module

- discord/command/debug.go
/debug clear command does not take user option properly.
This happens because /debug command's "**view**" and "**clear**" takes different length of option.
As you can see from the screenshot below, **view** operation has three options
Therefore.
option[0].Name = view
option[0].Option[0].Name = user or game-state
option[0].Option[0].Option[0].UserValue(s) = user:{input given by user}
However, clear command does not have third option so
option[0].Name = clear
option[0].Option[0].Name = user (because input option name is user)
option[0].Option[0].Option is always empty.
Therefore, userId will remain as default rather than user option given by user. (Person who raised the interaction command)
Accordingly, I propose to take second Option like in this PR.
Or change "**/debug clear user:**" …
> Fix Clear User Cache user option

- discord/command/help.go
This is almost meaningless, but just in case :P
> fix: add missing commands in help command

- Dockerfile
Disable cgo for swagger to avoid some errors on build.
> [builder 8/9] RUN swag init --parseDependency true
> 0.195 2023/07/20 05:42:57 Generate swagger docs....
> 0.195 2023/07/20 05:42:57 Generate general API Info, search dir:./
> ...
> 3.217 cgo: C compiler "gcc" not found: exec: "gcc": executable file not found in $PATH
> 3.392 cgo failed: [go tool cgo -objdir /tmp/net_C897375797 -- -I /tmp/net_C897375797 cgo_linux.go cgo_resnew.go cgo_socknew.go cgo_unix.go]: exit status 1
As discussed in Discord these errors can be ignored, but just disabling cgo can solve this instead of installing gcc, so I create this PR.
Tested locally and seems no side effect for generated docs.
> fix: disable cgo for swagger
